"""Nome da coluna atualizado

Revision ID: 6a4b1527c9e5
Revises: ec432b3350cc
Create Date: 2026-08-23 17:58:46.050481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4b1527c9e5'
down_revision: Union[str, Sequence[str], None] = 'ec432b3350cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('admin', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'admin')
    # ### end Alembic commands ###
