"""create inventory module

Revision ID: ec432b3350cc
Revises: 
Create Date: 2026-08-23 03:54:36.707715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec432b3350cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=256), nullable=False),
    sa.Column('user_password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='statusenum'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('stock_status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='statusenum'), server_default='ACTIVE', nullable=False),
    sa.Column('stock_description', sa.String(length=500), server_default='Not defined.', nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('stock_name')
    )
    op.create_table('movement',
    sa.Column('movement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_stock_id', sa.Integer(), nullable=False),
    sa.Column('to_stock_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('INPUT', 'OUTPUT', 'TRANSFER', name='movementtype'), nullable=False),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['from_stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['to_stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='statusenum'), server_default='ACTIVE', nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='product_available_quantity_check'),
    sa.CheckConstraint('cost_price >= 0', name='product_cost_price_check'),
    sa.CheckConstraint('sale_value >= 0', name='product_sale_value_check'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('movement_item',
    sa.Column('movement_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='movement_item_quantity_check'),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.movement_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('movement_item_id')
    )
    op.create_table('stock_item',
    sa.Column('stock_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_item')
    op.drop_table('movement_item')
    op.drop_table('product')
    op.drop_table('movement')
    op.drop_table('stock')
    op.drop_table('category')
    op.drop_table('app_user')
    # ### end Alembic commands ###
